#!/usr/bin/env bash
set -euo pipefail

: "${POSTGRES_DB:=integrator}"
: "${POSTGRES_USER:=postgres}"
: "${AUTH_DB_USERNAME:=auth_svc}"
: "${AUTH_DB_PASSWORD:=auth_svc}"
: "${ROUTE_DB_USERNAME:=route_svc}"
: "${ROUTE_DB_PASSWORD:=route_svc}"

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS route;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${AUTH_DB_USERNAME}') THEN
    CREATE ROLE ${AUTH_DB_USERNAME} LOGIN PASSWORD '${AUTH_DB_PASSWORD}';
  END IF;
END
\$\$;

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${ROUTE_DB_USERNAME}') THEN
    CREATE ROLE ${ROUTE_DB_USERNAME} LOGIN PASSWORD '${ROUTE_DB_PASSWORD}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${AUTH_DB_USERNAME};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${ROUTE_DB_USERNAME};

GRANT ALL PRIVILEGES ON SCHEMA auth TO ${AUTH_DB_USERNAME};
GRANT ALL PRIVILEGES ON SCHEMA route TO ${ROUTE_DB_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${AUTH_DB_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA route
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${ROUTE_DB_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${AUTH_DB_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA route
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${ROUTE_DB_USERNAME};
EOSQL